### ISSUE TITLE
Detect updates in pipeline assembly page is broken

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#421]
I had created multiple revisions of a CodeResource object and was using the automated 'detect updates' function to create new pipeline revisions without updating the respective Methods.  The new revisions were visible in the method-node dropdown (which implies that the corresponding Methods exist) but the new pipeline revision does not have the requested method assigned.  Will attempt to repro with demo fixtures.

**Comment by ArtPoon** [comment]
DO THIS ART

**Comment by ArtPoon** [comment]
* did fresh pull from `master`
* installed binaryornot and pytz
* updated `settings.py` using `settings_default.py` as template
* attempted to migrate database with `python manage.py migrate`:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/db/migrations/loader.py", line 178, in build_graph
    self.load_disk()
  File "/Library/Python/2.7/site-packages/Django-1.7.4-py2.7.egg/django/db/migrations/loader.py", line 104, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/art/git/Kive/kive/metadata/migrations/0016_set_cdt_names_20160215_1525.py", line 43, in <module>
    class Migration(migrations.Migration):
  File "/Users/art/git/Kive/kive/metadata/migrations/0016_set_cdt_names_20160215_1525.py", line 50, in Migration
    migrations.RunPython(set_cdt_names, reverse_code=migrations.RunPython.noop),
AttributeError: type object 'RunPython' has no attribute 'noop'
```

**Comment by rhliang** [comment]
Looks like you're using Django 1.7.4.  You'll need to upgrade to 1.9 at least.

**Comment by ArtPoon** [comment]
Yeah just realized that, thanks.

**Comment by ArtPoon** [comment]
* installed Django 1.9.7
```
  File "/Users/art/git/Kive/kive/kive/urls.py", line 4, in <module>
    from archive.ajax import MethodOutputViewSet, RunViewSet
  File "/Users/art/git/Kive/kive/archive/ajax.py", line 9, in <module>
    from rest_framework.decorators import detail_route, list_route
  File "/Library/Python/2.7/site-packages/djangorestframework-3.1.1-py2.7.egg/rest_framework/decorators.py", line 11, in <module>
    from rest_framework.views import APIView
  File "/Library/Python/2.7/site-packages/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 14, in <module>
    from rest_framework.response import Response
  File "/Library/Python/2.7/site-packages/djangorestframework-3.1.1-py2.7.egg/rest_framework/response.py", line 8, in <module>
    from django.core.handlers.wsgi import STATUS_CODE_TEXT
ImportError: cannot import name STATUS_CODE_TEXT
```

Looks like we are using code that has been [deprecated in Django 1.9.7](https://github.com/gitaarik/django-websocket-redis/commit/1c73764c0d02e0f4bf3c507ea854565346c4e80a).
Will attempt to do a similar patching.

**Comment by rhliang** [comment]
Hm.  Try upgrading your Django rest framework too.  I believe we require 3.3 now.

**Comment by ArtPoon** [comment]
Yup.  fwiw, I'm posting these notes to record the process of getting my Kive installation up to date (working out loud).  I'm not actually soliciting responses :)  Sorry for the spam.

**Comment by ArtPoon** [comment]
* installed `django-rest-framework-3.3.3`
```
WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
...
  File "/Library/Python/2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/migrations/loader.py", line 306, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/Library/Python/2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration archive.0102_relink_apps dependencies reference nonexistent parent node (u'metadata', u'0101_squashed')
```

On RL's suggestion, will nuke DB to accommodate changes that have accumulated in the project since my DB was last active.

**Comment by ArtPoon** [comment]
Hm, that didn't go smoothly:
```
CommandError: Database kive couldn't be flushed. Possible reasons:
  * The database isn't running or isn't configured correctly.
  * At least one of the expected database tables doesn't exist.
  * The SQL was invalid.
Hint: Look at the output of 'django-admin sqlflush'. That's the SQL this command wasn't able to run.
The full error: cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "librarian_symbolicdataset_groups_allowed" references "auth_group".
HINT:  Truncate table "librarian_symbolicdataset_groups_allowed" at the same time, or use TRUNCATE ... CASCADE.
```

**Comment by ArtPoon** [comment]
* used `postgres` user to drop Kive database
* `createdb kive`
* psql; `grant all privileges on database kive to kive;`
```
  File "/Library/Python/2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "method_coderesourcedependency" does not exist
```

**Comment by ArtPoon** [comment]
Squashed migrations in master branch may be causing problems.  Switched to `Isuse548` branch.
Migrations ran through.  Attempting to reproduce issue:
1. Create multiple revisions of a CodeResource
2. Create Method object for first CR.
3. Use "detect updates" function in pipeline assembly page to assign revised Method which has not been created by user.
4. Check which Method was assigned to revised pipeline.

**Comment by ArtPoon** [comment]
Created a new remap.py CR called "Version 2".  Toggling "check for updates" highlighted the remap step of demo MiSeq pipeline.  Dropdown had selected item "new: [driver updated (Version 2)]".  Added name and description field for revised pipeline.  Hitting submit resulted in 500 internal server error:
```
  File "/Users/art/git/Kive/kive/pipeline/serializers.py", line 411, in create
    dependency_revision = resource_map.get(
UnboundLocalError: local variable 'resource_map' referenced before assignment
```

**Comment by ArtPoon** [comment]
Tested and failed to reproduce on branch Issue548.  Close when this gets merged into master.

**Comment by donkirkby** [comment]
The Issue548 branch has been merged into master. Closing this issue.
