### ISSUE TITLE
Attempt to rerun pipeline step that did not keep intermediate outputs caused fleet to crash.

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#439]
While testing MiCall v7.0 on the Kive development server, I happened to uncheck the box for one of  the two `censor_fastq.py` Methods on the pipeline assembly page.  Running a revision of this pipeline caused the fleet to crash with the following log: 
```
2015-10-15 15:18:17[INFO]fleet.Manager.find_new_runs(): Starting run:
Pipeline: MiSeq pipelines:7 (v7.0-2)
User: kive
2015-10-15 15:18:21[INFO]fleet.Worker.receive_and_perform_task(): RunStep(123) received by rank 1: Runstep with PS [2: censor_fastq.py]
2015-10-15 15:18:21[ERROR]fleet.Worker.receive_and_perform_task(): [1] Task Runstep with PS [2: censor_fastq.py] failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive-dev/kive/fleet/workers.py", line 522, in receive_and_perform_task
    sandbox_result = sandbox.execute.finish_step(task_info_dict, self.rank)
  File "/usr/local/share/Kive-dev/kive/sandbox/execute.py", line 1701, in finish_step
    if not can_reuse["successful"] or can_reuse["fully reusable"]:
UnboundLocalError: local variable 'can_reuse' referenced before assignment
2015-10-15 15:18:22[ERROR]fleet.Manager.wait_for_polling(): Worker 1 reports a failed task (PK 123)
2015-10-15 15:18:22[INFO]fleet.Manager.main_procedure(): Manager shutting down.
2015-10-15 15:18:22[INFO]fleet.Worker.receive_and_perform_task(): Worker 3 shutting down.
2015-10-15 15:18:22[INFO]fleet.Worker.receive_and_perform_task(): Worker 1 shutting down.
2015-10-15 15:18:22[INFO]fleet.Worker.receive_and_perform_task(): Worker 2 shutting down.
2015-10-15 15:18:22[INFO]fleet.Worker.receive_and_perform_task(): Worker 4 shutting down.
[Bulbasaur:27223] [[13871,0],0] ORTE_ERROR_LOG: Not found in file routed_binomial.c at line 386
[Bulbasaur:27223] [[13871,0],0] ORTE_ERROR_LOG: A message is attempting to be sent to a process whose contact information is unknown in file rml_oob_send.c at line 104
[Bulbasaur:27223] [[13871,0],0] could not get route to [[13871,2],1]
```

**Comment by donkirkby** [comment]
This was fixed in commit 6e5cb4930e6cdfad875a6674cc180ddedb7dcead.

**Comment by ArtPoon** [comment]
Development server now running at commit 4edbb51c62bcfba6965ae4ca7d7bd8c5c7ae9f83.
Attempting to run a pipeline threw the following exception:
```
2015-10-15 16:02:14[INFO]fleet.Manager.find_new_runs(): Starting run:
Pipeline: MiSeq pipelines:9 (v7.0-4)
User: kive
2015-10-15 16:02:18[INFO]fleet.Worker.receive_and_perform_task(): RunStep(156) received by rank 1: Runstep with PS [4: prelim_map.py]
2015-10-15 16:02:19[ERROR]fleet.Worker.receive_and_perform_task(): [1] Task Runstep with PS [4: prelim_map.py] failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive-dev/kive/fleet/workers.py", line 522, in receive_and_perform_task
    self.rank,
  File "/usr/local/share/Kive-dev/kive/sandbox/execute.py", line 1727, in finish_step
    except (OperationalError, InternalError):
  File "/usr/local/share/Kive-dev/kive/sandbox/execute.py", line 1740, in _finish_step_h
    Helper for execute_step and finish_step.
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/usr/local/share/Kive-dev/kive/archive/models.py", line 2411, in create
    method_output.clean()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "are_checksums_OK" violates not-null constraint
```

**Comment by donkirkby** [comment]
Did you migrate the database? I think there's a migration that populates those fields.

**Comment by ArtPoon** [comment]
Checked out ff955eb81f58cc7e2d1539c4e6d62fac02ec291b for development server on cluster.
Migrated database, and successfully ran MiCall pipeline v7.0-18.  Closing.
