### ISSUE TITLE
Removing a dataset can crash the fleet

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#481]
If you remove a dataset while the fleet is checking the total size of the stored data, it can crash the fleet by removing a file just before the fleet manager checks its size or modification time.

```
2015-12-02 11:30:56[ERROR][8796]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 298, in main_procedure
    self.main_loop()
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 342, in main_loop
    Dataset.purge()
  File "/mnt/data/don/git/Kive/kive/archive/models.py", line 2359, in purge
    filedate = os.path.getmtime(filepath)
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/home/don/data/kive2/Datasets/2015_11/step9_g2p_yaaPW87.csv'
```

**Comment by ArtPoon** [comment]
Need to implement a check or try-except clause.  Size is checked hourly, and upon clear-out when data exceeds user-specified max capacity.  This will only happen if a user manually removes a data set while one of these processes is being executed.

**Comment by donkirkby** [comment]
This happened to me today when I was removing a run. It makes sense, because removing the run removes all the intermediate and output data sets.

**Comment by wrpscott** [comment]
The new idle tasks way of dataset purging should not have this issue,  59fce42
