### ISSUE TITLE
File exists when linking output file

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#495]
This error has crashed the fleet twice now.

    Traceback (most recent call last):
      File "/usr/local/share/Kive/kive/fleet/workers.py", line 535, in receive_and_perform_task
        sandbox_result = sandbox.execute.finish_step(task_info_dict, self.rank)
      File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1685, in finish_step
        curr_RSIC = finish_cable(curr_execute_dict, worker_rank)
      File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1524, in finish_cable
        output_CDT, recovering_record)
      File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1543, in _finish_cable_h
        cable.run_cable(input_SD_path, output_path, curr_record, curr_log)
      File "/usr/local/share/Kive/kive/pipeline/models.py", line 818, in run_cable
        link_result = os.link(source, output_path)
    OSError: [Errno 17] File exists

We added a work around in the code, but it has a bug in it.

**Comment by rhliang** [comment]
Possible cause: multiple steps with the same name.

Don will run a big diagnostic on his workstation and see if he can find the cause either way.  If we can track it down, we'll probably backport it to v0.6 rather than wait for v0.7.

**Comment by donkirkby** [comment]
I ran a steady stream of about 30 pipelines overnight on the master branch, and I didn't see this problem. I'll try it again using the 0.6 tag.

It doesn't happen that often in production, so I may just have to run longer.

**Comment by rhliang** [comment]
Same thing happened again in production just now, this time in a different place:

```
2016-02-17 14:33:17[ERROR]fleet.Worker.receive_and_perform_task(): [21] Task RunOutputCable("coverage_maps_tar") failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 537, in receive_and_perform_task
    sandbox_result = sandbox.execute.finish_cable(task_info_dict, self.rank)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1524, in finish_cable
    output_CDT, recovering_record)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1543, in _finish_cable_h
    cable.run_cable(input_SD_path, output_path, curr_record, curr_log)
  File "/usr/local/share/Kive/kive/pipeline/models.py", line 818, in run_cable
    link_result = os.link(source, output_path)
OSError: [Errno 17] File exists
```

**Comment by rhliang** [comment]
Just for posterity, I'm going to record what I'm doing here: four clinical MiSeq runs were interrupted by the fleet crash, so I'm going to manually restart them.

**Comment by rhliang** [comment]
A little Google searching reveals a possible culprit: the `O_EXCL` flag to the system's `open()` functionality is broken for NFS.

https://www.freebsd.org/cgi/man.cgi?query=open&sektion=2&apropos=0&manpath=redhat

(look at the description for `O_EXCL`)

**Comment by rhliang** [comment]
Having guarded against this but not having actually observed it again, Don and I talked about moving this to the next milestone.  If we manage to observe the issue and our fix worked, we can then close this issue.

**Comment by donkirkby** [comment]
The code that is supposed to work around this exception has a flaw. It doesn't call `log.stop()` when the exception is thrown. That causes a validation error later on.

Here are the errors in the log:

```
2016-03-09 13:21:21[INFO]fleet.Worker.receive_and_perform_task(): RunStep(272614) received by rank 43: Runstep with PS [5: remap.py]
2016-03-09 13:35:17[WARNING]pipeline.models.run_cable(): OSError occurred while linking /data/kive/Sandboxes/usermicall_run8236_QypMJ9/step3/output_data/step3_censored.raw to /data/kive/Sandboxes/usermicall_run8236_QypMJ9/step5/input_data/step5_fastq2.raw
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/pipeline/models.py", line 853, in run_cable
    os.link(source, output_path)
OSError: [Errno 17] File exists
2016-03-09 13:41:08[ERROR]fleet.Worker.receive_and_perform_task(): [43] Task Runstep with PS [5: remap.py] failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 906, in receive_and_perform_task
    sandbox_result = Sandbox.finish_step(task_info_dict, self.rank, self.interface.stop_run_callback)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1535, in finish_step
    curr_RSIC = Sandbox.finish_cable(curr_execute_dict, worker_rank)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1444, in finish_cable
    curr_record.link_execrecord(curr_ER, reused=False)
  File "/usr/local/share/Kive/kive/archive/models.py", line 920, in link_execrecord
    self.clean()
  File "/usr/local/share/Kive/kive/archive/models.py", line 2238, in clean
    elif not self._clean_not_reused():
  File "/usr/local/share/Kive/kive/archive/models.py", line 2045, in _clean_not_reused
    if not RunComponent._clean_not_reused(self):
  File "/usr/local/share/Kive/kive/archive/models.py", line 994, in _clean_not_reused
    raise ValidationError("{}; execrecord should not be set".format(general_error))
ValidationError: [u'RunSIC "RunComponent id 277386" is not reused and does not have a complete log; execrecord should not be set']
```

**Comment by donkirkby** [comment]
The problem occurred again on March 22, and the workaround was successful. Closing the issue.
