### ISSUE TITLE
Data migration that calls `manage.py loaddata` fails

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#518]
After adding a name field to CompoundDatatype (issue #465), I'm finding that the test suite fails to run because of an error during database setup on one of our data migrations.  When I rolled back the migrations to that point, re-migrating failed with the same error.  The same error appears yet again if I try `manage.py loaddata` on the fixtures that the data migration loads.

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 100, in loaddata
    self.load_label(fixture_label)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 158, in load_label
    obj.save(using=self.using)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/core/serializers/base.py", line 201, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/models/base.py", line 793, in _save_table
    forced_update)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/models/base.py", line 843, in _do_update
    return filtered._update(values) > 0
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/models/query.py", line 645, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1149, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Problem installing fixture '/Users/rliang/Documents/Research/Copperfish/copperfish/kive/metadata/fixtures/initial_data.json': Could not load metadata.CompoundDatatype(pk=1): column "name" of relation "metadata_compounddatatype" does not exist
LINE 1: ...TE "metadata_compounddatatype" SET "user_id" = 1, "name" = '...
```

I suspect the issue is that `loaddata` uses serializers that use the current code (which has a `name` field on CompoundDatatype) to load the fixtures.  This is a problem because the data migration exists at a point in the migration history where the CompoundDatatype model doesn't have the `name` field.  I'm going to rewrite that data migration to actually populate the system with Python commands; I think I have a script somewhere that did exactly that.

**Comment by rhliang** [comment]
Note: the code in question was actually already in the repository as `metadata/load_data.py`.  I'll update it and put it back into use.

**Comment by rhliang** [comment]
Implementing the contents of `initial_data.json` in Python code appears to have worked.  Because I needed to specify creation dates for the Datatypes, and Django was giving me warnings because I was still using naive datetimes, I moved to using aware datetimes.  This means that you will have to install the `pytz` module, which can be easily done using `pip`.
