### ISSUE TITLE
Can't migrate or run server after pull

### ISSUE THREAD

**Issue by jnak-cfe** [cfe-lab/Kive#520]
Stack track:

```
Unhandled exception in thread started by <function wrapper at 0x10a71cf50>
Traceback (most recent call last):
  File "/Users/james/Library/Python/2.7/lib/python/site-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "/Users/james/Library/Python/2.7/lib/python/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    self.check_migrations()
  File "/Users/james/Library/Python/2.7/lib/python/site-packages/django/core/management/commands/runserver.py", line 159, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/james/Library/Python/2.7/lib/python/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/james/Library/Python/2.7/lib/python/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/james/Library/Python/2.7/lib/python/site-packages/django/db/migrations/loader.py", line 178, in build_graph
    self.load_disk()
  File "/Users/james/Library/Python/2.7/lib/python/site-packages/django/db/migrations/loader.py", line 104, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/james/git/Kive/kive/metadata/migrations/0016_set_cdt_names_20160215_1525.py", line 43, in <module>
    class Migration(migrations.Migration):
  File "/Users/james/git/Kive/kive/metadata/migrations/0016_set_cdt_names_20160215_1525.py", line 50, in Migration
    migrations.RunPython(set_cdt_names, reverse_code=migrations.RunPython.noop),
AttributeError: type object 'RunPython' has no attribute 'noop'
```

**Comment by rhliang** [comment]
Have you upgraded to Django 1.9?  This is a thing that was introduced in v1.8.

**Comment by jnak-cfe** [comment]
D'oh. Thanks.
