### ISSUE TITLE
Failed run step crashes fleet

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#522]
I ran a pipeline on an invalid input, and it crashed the fleet. The pipeline had nine steps, and the third one failed because of an invalid input. It also displayed the wrong status in the list of runs.

Expected status: `**!......-...............`

Actual status: `**!******-...............`

Here is the end of the fleet log:

    2016-02-29 14:29:15[INFO][20672]fleet.Worker.receive_and_perform_task(): RunStep(484490) received by rank 1: Runstep with PS [3: censor_fastq.py]
    2016-02-29 14:29:17[INFO][20666]fleet.Manager.worker_finished(): Worker 1 reports task with PK 484490 is finished
    2016-02-29 14:29:17[INFO][20666]fleet.Manager.note_progress(): Cleaning up failed run "Run with pipeline [MiSeq pipelines:36 (trim censored tail)]" (pk=12521) (Pipeline: MiSeq pipelines:36 (trim censored tail), User: micall)
    2016-02-29 14:29:18[ERROR][20666]fleet.Manager.main_procedure(): Manager failed.
    Traceback (most recent call last):
      File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 487, in main_procedure
        self.main_loop()
      File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 523, in main_loop
        if not self.wait_for_polling(time_to_poll):
      File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 559, in wait_for_polling
        self.worker_finished(lord_rank, result_pk)
      File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 507, in worker_finished
        self.note_progress(lord_rank, task_finished)
      File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 476, in note_progress
        curr_sdbx.run.complete_clean(use_cache=True)
      File "/mnt/data/don/git/Kive/kive/archive/models.py", line 495, in complete_clean
        self.clean()
      File "/mnt/data/don/git/Kive/kive/archive/models.py", line 213, in clean
        runstep.clean()
      File "/mnt/data/don/git/Kive/kive/archive/models.py", line 1653, in clean
        if not self._clean_cables_in():
      File "/mnt/data/don/git/Kive/kive/archive/models.py", line 1441, in _clean_cables_in
        rsic.complete_clean()
      File "/mnt/data/don/git/Kive/kive/archive/models.py", line 1191, in complete_clean
        raise ValidationError('{} "{}" is not complete'.format(self.__class__.__name__, self))
    ValidationError: [u'RunSIC "RunComponent id 484542" is not complete']
    2016-02-29 14:29:19[INFO][20672]fleet.Worker.receive_and_perform_task(): Worker 1 shutting down.
    2016-02-29 14:29:19[INFO][20679]fleet.Worker.receive_and_perform_task(): Worker 8 shutting down.
    2016-02-29 14:29:19[INFO][20681]fleet.Worker.receive_and_perform_task(): Worker 10 shutting down.
    2016-02-29 14:29:19[INFO][20682]fleet.Worker.receive_and_perform_task(): Worker 11 shutting down.
    2016-02-29 14:29:19[INFO][20673]fleet.Worker.receive_and_perform_task(): Worker 2 shutting down.
    2016-02-29 14:29:19[INFO][20675]fleet.Worker.receive_and_perform_task(): Worker 4 shutting down.
    2016-02-29 14:29:19[INFO][20676]fleet.Worker.receive_and_perform_task(): Worker 5 shutting down.
    2016-02-29 14:29:19[INFO][20677]fleet.Worker.receive_and_perform_task(): Worker 6 shutting down.
    2016-02-29 14:29:19[INFO][20678]fleet.Worker.receive_and_perform_task(): Worker 7 shutting down.
    2016-02-29 14:29:19[INFO][20680]fleet.Worker.receive_and_perform_task(): Worker 9 shutting down.
    2016-02-29 14:29:19[INFO][20674]fleet.Worker.receive_and_perform_task(): Worker 3 shutting down.

**Comment by donkirkby** [comment]
I tested the changes, and it doesn't crash the fleet any more.
