### ISSUE TITLE
Publish pipeline button is broken

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#528]
When I click the button to publish a pipeline, nothing happens. I see this error in the log:

```
Internal Server Error: /api/pipelines/116
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 115, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 99, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to localhost:8000/api/pipelines/116/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2016-03-09 10:16:30[ERROR][4557]django.request.handle_uncaught_exception(): Internal Server Error: /api/pipelines/116
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 115, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 99, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to localhost:8000/api/pipelines/116/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[09/Mar/2016 10:16:30] "PATCH /api/pipelines/116 HTTP/1.1" 500 17988
```

**Comment by jnak-cfe** [comment]
Not sure why we're using PATCH and not POST—but it was easy to add the trailing slash.
Remind me, are >1 published versions of a pipeline family supposed to be allowed?

**Comment by donkirkby** [comment]
Yes, multiple published versions are allowed.

**Comment by rhliang** [comment]
We're using PATCH because it's modifying the PipelineFamily rather than creating anything.

**Comment by jnak-cfe** [comment]
Ok, that's working, then
