### ISSUE TITLE
Fleet crashes when more threads are requested than there are workers

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#540]
```
ValidationError: [u'Stopwatch "Run with pipeline [MiSeq:1]" does not have a start time but it has an end time']
```

![runs_error](https://cloud.githubusercontent.com/assets/6126553/13719453/98858d08-e7aa-11e5-82cf-3407b44c4828.png)

**full stack:**

```
Traceback (most recent call last):
  File "/Users/james/git/Kive/kive/fleet/workers.py", line 487, in main_procedure
    self.main_loop()
  File "/Users/james/git/Kive/kive/fleet/workers.py", line 526, in main_loop
    self.find_new_runs()
  File "/Users/james/git/Kive/kive/fleet/workers.py", line 593, in find_new_runs
    run_to_process.clean()
  File "/Users/james/git/Kive/kive/archive/models.py", line 202, in clean
    stopwatch.models.Stopwatch.clean(self)
  File "/Users/james/git/Kive/kive/stopwatch/models.py", line 31, in clean
    raise ValidationError('Stopwatch "{}" does not have a start time but it has an end time'.format(self))
ValidationError: [u'Stopwatch "Run with pipeline [MiSeq:1]" does not have a start time but it has an end time']
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/james/git/Kive/kive/fleet/management/commands/runfleet.py", line 32, in handle
    manager.main_procedure()
  File "/Users/james/git/Kive/kive/fleet/workers.py", line 491, in main_procedure
    self.interface.shut_down_fleet()
  File "/Users/james/git/Kive/kive/fleet/workers.py", line 138, in shut_down_fleet
    self.comm.send(dest=rank, tag=Worker.SHUTDOWN)
  File "MPI/Comm.pyx", line 1172, in mpi4py.MPI.Comm.send (src/mpi4py.MPI.c:106382)
```

**Comment by donkirkby** [comment]
I suspect this is a bug in the code that fails a run when there are not enough workers to supply the number of threads it needs. It probably started happening when we combined RunToProcess with Run.

**Comment by jnak-cfe** [comment]
In the meantime, should I just start with 4 workers?

**Comment by rhliang** [comment]
Yes, that will work.  It's not a bug, it's a feature!  Or at least it was intentional.  A Run that's started with a fleet that can't handle it gets cancelled and gets an ExceedsSystemCapabilities object stuck to it.

**Comment by jnak-cfe** [comment]
Hahaha.

**Comment by ArtPoon** [comment]
Please post commit number where you saw the problem, thanks!

**Comment by jnak-cfe** [comment]
f2c840ec26ed6095c2c3e3f6fa799e8b9c811782

Sorry; thought it was in master. It is not. (but that probably doesn't affect things)

**Comment by rhliang** [comment]
This will also be deprecated when Slurm execution is complete.
