### ISSUE TITLE
Stop run properly when short of workers

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#562]
Steps to reproduce:
1. Set up a pipeline where at least one step requires more than one thread.
2. Launch the fleet with only one worker.
3. Start the pipeline.

Expected result: run stops with an error message about too many threads. Start and stop times are set.

Actual result: error message is correct, but start and stop times are not set. The fleet crashes because it keeps trying to run the same run again.

```
2016-06-21 09:43:06[INFO][26116]fleet.Manager._startup(): Manager started on host nimoy
2016-06-21 09:43:06[INFO][26116]fleet.Manager.take_rollcall(): Worker 1 on host nimoy has reported for duty
2016-06-21 09:43:11[INFO][26116]fleet.Manager.find_new_runs(): Cannot run Pipeline MiSeq pipelines:64 (v7.3 NS5a positions) for user kive: 4 threads required, 1 available
2016-06-21 09:43:16[INFO][26116]fleet.Manager.find_new_runs(): Cannot run Pipeline MiSeq pipelines:64 (v7.3 NS5a positions) for user kive: 4 threads required, 1 available
2016-06-21 09:43:16[ERROR][26116]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 895, in main_procedure
    self.main_loop()
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 882, in main_loop
    self.find_new_runs()
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 737, in find_new_runs
    esc.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "archive_exceedssystemcapabilities_run_id_key"
DETAIL:  Key (run_id)=(15531) already exists.

2016-06-21 09:43:16[INFO][26120]fleet.Worker.receive_and_perform_task(): Worker 1 shutting down.
```

**Comment by rhliang** [comment]
Closing because this isn't a problem anymore now that we're using Slurm.
