### ISSUE TITLE
Can't create a new pipeline family

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#600]
I can create a new pipeline family through the API, and I can create a new pipeline within a family, but creating a new pipeline family through the web site gives this error:

    [19/Aug/2016 12:21:27] "POST /api/pipelinefamilies/ HTTP/1.1" 201 370
    Internal Server Error: /api/pipelines/
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
        response = self.process_exception_by_middleware(e, request)
      File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
        return view_func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
        response = self.handle_exception(exc)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
        response = handler(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 20, in create
        serializer.is_valid(raise_exception=True)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 213, in is_valid
        self._validated_data = self.run_validation(self.initial_data)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 407, in run_validation
        value = self.to_internal_value(data)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 437, in to_internal_value
        validated_value = field.run_validation(primitive_value)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 479, in run_validation
        (is_empty_value, data) = self.validate_empty_values(data)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 453, in validate_empty_values
        return (True, self.get_default())
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 437, in get_default
        self.default.set_context(self)
      File "/mnt/data/don/git/Kive/kive/pipeline/serializers.py", line 169, in set_context
        name=rev_num_field.parent.initial_data.get("family")
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
        self.model._meta.object_name
    DoesNotExist: PipelineFamily matching query does not exist.
    2016-08-19 12:21:27[ERROR][19015]django.request.handle_uncaught_exception(): Internal Server Error: /api/pipelines/
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
        response = self.process_exception_by_middleware(e, request)
      File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
        return view_func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
        response = self.handle_exception(exc)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
        response = handler(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 20, in create
        serializer.is_valid(raise_exception=True)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 213, in is_valid
        self._validated_data = self.run_validation(self.initial_data)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 407, in run_validation
        value = self.to_internal_value(data)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 437, in to_internal_value
        validated_value = field.run_validation(primitive_value)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 479, in run_validation
        (is_empty_value, data) = self.validate_empty_values(data)
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 453, in validate_empty_values
        return (True, self.get_default())
      File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 437, in get_default
        self.default.set_context(self)
      File "/mnt/data/don/git/Kive/kive/pipeline/serializers.py", line 169, in set_context
        name=rev_num_field.parent.initial_data.get("family")
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
        self.model._meta.object_name
    DoesNotExist: PipelineFamily matching query does not exist.

**Comment by rhliang** [comment]
Problem appears to be a snippet of Javascript that fell through the cracks.  The function `submitPipelineFamilyAjax` didn't take enough information to create both the PipelineFamily and the new Pipeline.  I've updated it so it works again.
