### ISSUE TITLE
Fleet crashes when run permissions are incompatible

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#601]
I uploaded a dataset and forgot to grant permissions to everyone. Then I used it as an input for a run and granted permissions to everyone. It looks like the step finished, but the fleet crashed when running the output cable.

It would be nice if the error message for permissions problems would give more information about why permissions cannot be granted.

```
2016-08-19 19:55:18[ERROR]fleet.Worker.record_exception(): [1] Task Runstep with PS [1: sums_and_products.py] failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 1097, in receive_and_perform_task
    sandbox_result = Sandbox.finish_step(task_info_dict, self.rank, self.interface.stop_run_callback)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1711, in finish_step
    curr_RSIC = Sandbox.finish_cable(curr_execute_dict, worker_rank)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1612, in finish_cable
    [output_dataset]
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/usr/local/share/Kive/kive/librarian/models.py", line 1372, in create
    execrecord.complete_clean()
  File "/usr/local/share/Kive/kive/librarian/models.py", line 1466, in complete_clean
    self.clean()
  File "/usr/local/share/Kive/kive/librarian/models.py", line 1401, in clean
    eri.clean()
  File "/usr/local/share/Kive/kive/librarian/models.py", line 1750, in clean
    self.execrecord.generating_run.validate_restrict_access([self.dataset])
  File "/usr/local/share/Kive/kive/metadata/models.py", line 485, in validate_restrict_access
    raise groups_error
ValidationError: [u'Group(s) Everyone cannot be granted access']
2016-08-19 19:55:18[INFO]fleet.Worker.receive_and_perform_task(): Worker 1 shutting down.
```

**Comment by rhliang** [comment]
Let's double-check that this is still an issue.  Proper solution is probably to prohibit the run from even starting, perhaps caught at the same stage as #570, if it even still exists as a problem.
