### ISSUE TITLE
Update demo fixture with new MiCall

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#603]
The old MiCall depends on HyPhy, R, and Ruby, but those dependencies have been removed in the latest versions of MiCall. Generate a new demo fixture that will be easier to try out, because it only depends on bowtie2.

**Comment by wrpscott** [comment]
closed with commit on september 26.

**Comment by donkirkby** [comment]
Reopening, because I tried running the pipeline and got this error:

```
2016-09-27 15:09:45[ERROR][16971]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 901, in main_procedure
    self.main_loop()
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 888, in main_loop
    self.find_new_runs(time_to_poll)
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 743, in find_new_runs
    self.start_run(run_to_process)
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 272, in start_run
    new_sdbx.advance_pipeline()
  File "/mnt/data/don/git/Kive/kive/sandbox/execute.py", line 404, in advance_pipeline
    self.run_plan.load(self.run, self.inputs)
  File "/mnt/data/don/git/Kive/kive/sandbox/execute.py", line 2049, in load
    output_index = cable.source.definite.dataset_idx-1
  File "/mnt/data/don/git/Kive/kive/transformation/models.py", line 327, in definite
    return self.transformationoutput
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related_descriptors.py", line 355, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: TransformationXput has no transformationoutput.
```

Also got this error when trying to revise the pipeline (changed nothing and clicked submit):

>outcables.source_step: Ensure this value is greater than or equal to 1.
