### ISSUE TITLE
Removing a dataset doesn't remove pending runs

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#637]
Steps to reproduce:

1. Reset to the demo database.
2. Upload another copy of the `script_1_sum_and_products_input.csv` file. Change a number, and name the dataset `pairs2.csv` to make it easy to find.
3. Without starting the fleet, create a new run with the sums and products pipeline and the new dataset.
4. Delete the new dataset.

Expected behaviour: it should warn you that it's going to delete the dataset and the run, then it should delete both of them, or it should not allow you to delete the dataset while there's an active run.

Actual behaviour: it only warns you that it's going to delete the dataset, and it only deletes the dataset. Because the run is now missing its input, you get this error when you launch the fleet:

```
2016-11-16 10:35:51[ERROR][6828]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 906, in main_procedure
    self.main_loop()
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 893, in main_loop
    self.find_new_runs(time_to_poll)
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 748, in find_new_runs
    self.start_run(run_to_process)
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 271, in start_run
    new_sdbx = Sandbox(run=run_to_start)
  File "/mnt/data/don/git/Kive/kive/sandbox/execute.py", line 104, in __init__
    self.pipeline.check_inputs(self.inputs)
  File "/mnt/data/don/git/Kive/kive/pipeline/models.py", line 310, in check_inputs
    .format(self, self.inputs.count(), len(inputs)))
ValueError: Pipeline "sums_and_products_verbose:1 (sum_and_products_verbose)" expects 1 inputs, but 0 were supplied
```

**Comment by rhliang** [comment]
Problem is in `build_removal_plan`: the affected Runs are not identified because it's looking for inputs to ExecRecords, not RunInput objects.

**Comment by donkirkby** [comment]
The new container runs do get checked, so there's nothing to fix there.
We're going to remove the old runs soon, so it's not worth fixing this bug. Closing the issue.
