### ISSUE TITLE
Problem with the idle_dataset_purge idle task

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#654]
Just saw this as I was running a test.  It appears `librarian.models.idle_dataset_purge` had an issue.  Here's the log output:

```
2017-01-10 11:34:10[INFO]fleet.Manager._do_idle_tasks(): Running an idle task....
2017-01-10 11:34:10[ERROR]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/home/rliang/MacHome/Documents/Research/Copperfish/copperfish/kive/fleet/workers.py", line 316, in main_procedure
    self.main_loop()
  File "/home/rliang/MacHome/Documents/Research/Copperfish/copperfish/kive/fleet/workers.py", line 303, in main_loop
    self._do_idle_tasks(poll_until)
  File "/home/rliang/MacHome/Documents/Research/Copperfish/copperfish/kive/fleet/workers.py", line 147, in _do_idle_tasks
    jobtodo.send(time_limit)
  File "/home/rliang/MacHome/Documents/Research/Copperfish/copperfish/kive/librarian/models.py", line 1330, in idle_dataset_purge
    checker = cls.filepurger.regenerator(exclude_set)
UnboundLocalError: local variable 'exclude_set' referenced before assignment
```

**Comment by wrpscott** [comment]
This issue is resolved in the slurm branch. Will fix it in the main branch for the next non-slurm release.
