### ISSUE TITLE
Missing external dataset crashes fleet

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#661]
I haven't tried to reproduce this yet, but here's what I think happened.

1. Upload an external dataset. Currently, the only way to do this is through the API.
2. Rename or delete the file on the file system.
3. Start an analysis run with the new dataset as an input. Notice that it is listed as missing when you select it as an input.
4. Start the run, and wait for the step that uses the missing input to begin.

Expected behaviour: it shouldn't let you start a run with a missing input, and if an input goes missing between the run start and the run step start, it should fail the run.

Actual behaviour: it lets you start the run, then crashes the fleet when it can't find the input.

    2017-02-10 15:55:13[ERROR][9205]fleet.Manager.main_procedure(): Manager failed.
    Traceback (most recent call last):
      File "/path/Kive/kive/fleet/workers.py", line 965, in main_procedure
        self.main_loop()
      File "/path/Kive/kive/fleet/workers.py", line 949, in main_loop
        if not self.wait_for_polling(time_to_poll):
      File "/path/Kive/kive/fleet/workers.py", line 754, in wait_for_polling
        self.worker_finished(lord_rank, result_pk)
      File "/path/Kive/kive/fleet/workers.py", line 612, in worker_finished
        curr_sdbx.advance_pipeline(task_completed=just_finished["task"])
      File "/path/Kive/kive/sandbox/execute.py", line 694, in advance_pipeline
        curr_RS = self.reuse_or_prepare_step(step, run_to_resume, step_inputs, run_dir)
      File "/path/Kive/kive/sandbox/execute.py", line 1171, in reuse_or_prepare_step
        self.queue_recovery(missing_data, invoking_record=curr_RS)
      File "/path/Kive/kive/sandbox/execute.py", line 1264, in queue_recovery
        .format(dataset_to_recover, self.pipeline))
    ValueError: Dataset "S282064" is an input to Pipeline "MiSeq pipelines:81 (v7.7 Python 3)" and cannot be recovered

**Comment by wrpscott** [comment]
Simply viewing such a file that has been renamed (in 'Uploaded datasets') will crash the server. Will fix this first, then move on to pipeline inputs.
