### ISSUE TITLE
Fleet may crash when runs are deleted

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#685]
Got this error while I was deleting runs on Bulbasaur:

```
2017-05-02 16:40:37[ERROR]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 351, in main_procedure
    self.main_loop()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 324, in main_loop
    self.monitor_queue(poll_until)
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 126, in monitor_queue
    foreman.monitor_queue()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 663, in monitor_queue
    self.sandbox.run.refresh_from_db()
  File "/home/kivefleet/vkive/lib/python2.7/site-packages/django/db/models/base.py", line 584, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/home/kivefleet/vkive/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Run matching query does not exist.
```

Looks like the Foreman isn't robust to runs that it was watching for being deleted.

**Comment by donkirkby** [comment]
Irrelevant since we are removing support for old pipelines.
