### ISSUE TITLE
Purge task let disk fill up

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#697]
Several things need improvement in the purging task:

* [ ] Make the dataset purge task log messages to the `kive_fleet.log` file when it runs a purge. (It writes on Bulbasaur, but not on Octomore.)
* [ ] Stop the log purge from writing messages when it doesn't run a purge. (It writes many messages on Bulbasaur.)
* [ ] Make the purge tasks run, even when the fleet is under constant load, such as a new release of MiCall that is reprocessing all the old data.
* [ ] Consider running the purge tasks under Slurm, and launch them once an hour.

Over the weekend, the `/data` disk filled up, and the fleet manager shut down with this error:

```
2017-07-02 03:37:15[ERROR]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 351, in main_procedure
    self.main_loop()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 324, in main_loop
    self.monitor_queue(poll_until)
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 126, in monitor_queue
    foreman.monitor_queue()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 581, in monitor_queue
    bookkeeping_job = self.submit_runstep_bookkeeping(task, task_dict["info_path"])
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 850, in submit_runstep_bookkeeping
    self.sandbox
  File "/usr/local/share/Kive/kive/fleet/slurmlib.py", line 909, in submit_step_bookkeeping
    book_cmd, book_args)
  File "/usr/local/share/Kive/kive/fleet/slurmlib.py", line 307, in _create_wrapperfile
    fo.write(template.format(preamble, cmd, args))
IOError: [Errno 28] No space left on device
```

The disk was using more than the configured 5TB:
```
$ sudo du -d 1 -h /data
584G    /data/kive_octomore_original
12M    /data/miseq
6.2T    /data/kive
7.4M    /data/miseq_octomore_original
16K    /data/lost+found
128G    /data/raw_data_test
6.9T    /data
```
I deleted the `octomore_original` folders and restarted the fleet manager. It immediately started deleting files, but it didn't write any messages about the purge in the `kive_fleet.log` file.

**Comment by donkirkby** [comment]
We filled the `/data` drive again. I removed some old test data to make room, and then restarted the fleet manager. It immediately started purging sandboxes that brought the disk usage down to 65%.

**Comment by donkirkby** [comment]
Are there any file system events that might be useful to monitor? That might be more efficient than scanning the folders. [PyInotify] might be useful.

[PyInotify]: https://github.com/dsoprea/PyInotify

**Comment by donkirkby** [comment]
Everything seems to work fine on Bulbasaur, so maybe it's just been a long time since Octomore ran a purge. I'll monitor disk usage on Octomore for a while.

```
$ date && du -h --summarize /data/kive/Datasets
Tue Jul 31 10:11:40 PDT 2018
3.3T	/data/kive/Datasets
```

**Comment by donkirkby** [comment]
The purge did write messages to the kive fleet log on Octomore.

```
2018-09-25 19:50:22[INFO]librarian.Dataset.purge(): Dataset purge triggered at 4.0 TB over 575158 files.
2018-09-25 20:01:47[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_04/step4_prelim_KxLQZH7.csv', deleting it.
2018-09-25 20:01:47[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_04/step4_prelim_TbyJIiw.csv', deleting it.
2018-09-25 20:02:56[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step6_aligned_ZU6DbFR.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step6_conseq_ins_xDcKtgR.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step6_aligned_Gz76RVr.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step6_aligned_KN05E2q.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step6_failed_read_MsdGD8B.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step6_conseq_ins_Mm8PmCe.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step6_conseq_ins_RqlaauZ.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step6_clipping_csv_Eu0onSK.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step5_remap_ZHdKM7g.csv', deleting it.
2018-09-25 20:02:57[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_05/step2_trimmed1_fastq_dl5Bb7Y.raw', deleting it.
2018-09-25 20:06:13[WARNING]librarian.Dataset.purge(): No dataset matches file u'Datasets/2018_06/step2_aligned_csv_lqgFzyZ.csv', deleting it.
2018-09-25 21:37:43[INFO]librarian.Dataset.purge(): Dataset purge finished. Leaving 2.0 TB over 115662 files.
```
