### ISSUE TITLE
Missing slurm logs crash fleet

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#701]
Two or three times now, I've seen the fleet crash with an error message like this:

```
2017-08-03 16:16:13[INFO]fleet.Foreman.worker_finished(): Run Run with pipeline [mixed-hcv:34 (v7.5.1 change bowtie2 invocation)] (pk=282612) reports task with PK 9702463 is finished
2017-08-03 16:16:18[ERROR]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 351, in main_procedure
    self.main_loop()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 324, in main_loop
    self.monitor_queue(poll_until)
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 126, in monitor_queue
    foreman.monitor_queue()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 560, in monitor_queue
    "Should be exactly 1 stdout log but found this: {}".format(stdout_log)
AssertionError: Should be exactly 1 stdout log but found this: []
```

I don't know which file was missing, but all the expected log files seem to be in the sandbox folder.

* [x] at least log the search pattern of the file you're looking for
* [x] ~~try adding a delay if the file is missing~~ (Haven't seen this recently, so I just added the logging part.)

**Comment by donkirkby** [comment]
Coincidence? Several phylowatch jobs were submitted to Slurm at 16:15 and 16:16. When I tried launching the Kive fleet again, it crashed after a few minutes.

```
2017-08-03 16:40:24[INFO]fleet.slurmlib.slurm_is_alive(): squeue passed: True
...
2017-08-03 16:48:51[ERROR]fleet.slurmlib.submit_job(): sbatch returned an error code '1'

Command list:
['sbatch', '-D', '/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1', '--gid=1004', '-J', 'r282675s\\(1\\,\\)driver\\[random\\-primer\\-hcv\\.py\\]', '-p', 'kive-
slow', '-s', '--uid=1003', '-c', '4', '--export=PYTHONPATH=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1', '--export=all', '--output=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/logs/step1_stdout_slurmID%J_node%N.txt', '--error=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/logs/step1_stderr_slurmID%J_node%N.txt', '--dependency=afterok:1473698', '--kill-on-invalid-dep=yes', u'/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/random-primer-hcv.pyKHF4kh']

Output:


stderr:
sbatch: error: slurm_receive_msg: Socket timed out on send/recv operation
sbatch: error: Batch job submission failed: Socket timed out on send/recv operation
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/slurmlib.py", line 383, in submit_job
    out_str = sp.check_output(cmd_lst, stderr=f)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['sbatch', '-D', '/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1', '--gid=1004', '-J', 'r282675s\\(1\\,\\)driver\\[random\\-primer\\-hcv\\.py\\]', '-p', 'kive-slow', '-s', '--uid=1003', '-c', '4', '--export=PYTHONPATH=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1', '--export=all', '--output=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/logs/step1_stdout_slurmID%J_node%N.txt', '--error=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/logs/step1_stderr_slurmID%J_node%N.txt', '--dependency=afterok:1473698', '--kill-on-invalid-dep=yes', u'/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/random-primer-hcv.pyKHF4kh']' returned non-zero exit status 1
2017-08-03 16:48:56[ERROR]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 351, in main_procedure
    self.main_loop()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 323, in main_loop
    self.find_new_runs(poll_until)
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 189, in find_new_runs
    foreman.start_run()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 746, in start_run
    self.submit_ready_tasks()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 780, in submit_ready_tasks
    slurm_info = self.submit_runstep(task)
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 830, in submit_runstep
    slurm_sched_class=self.slurm_sched_class
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1950, in submit_step_execution
    job_name=job_name
  File "/usr/local/share/Kive/kive/fleet/slurmlib.py", line 383, in submit_job
    out_str = sp.check_output(cmd_lst, stderr=f)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['sbatch', '-D', '/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1', '--gid=1004', '-J', 'r282675s\\(1\\,\\)driver\\[random\\-primer\\-hcv\\.py\\]', '-p', 'kive-slow', '-s', '--uid=1003', '-c', '4', '--export=PYTHONPATH=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1', '--export=all', '--output=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/logs/step1_stdout_slurmID%J_node%N.txt', '--error=/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/logs/step1_stderr_slurmID%J_node%N.txt', '--dependency=afterok:1473698', '--kill-on-invalid-dep=yes', u'/data/kive/Sandboxes/usermicall_run282675_Jr2btg/step1/random-primer-hcv.pyKHF4kh']' returned non-zero exit status 1
```
