### ISSUE TITLE
Fleet crashes when two runs restore the same dataset

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#722]
I got this fleet crash when rerunning a bunch of old pipeline runs:

```
2017-12-14 14:30:01[ERROR]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 390, in main_procedure
    self.main_loop()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 363, in main_loop
    self.monitor_queue(poll_until)
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 154, in monitor_queue
    foreman.monitor_queue()
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 783, in monitor_queue
    self.worker_finished(task)
  File "/usr/local/share/Kive/kive/fleet/workers.py", line 1047, in worker_finished
    self.sandbox.advance_pipeline(task_completed=finished_task)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 705, in advance_pipeline
    curr_RS = self.reuse_or_prepare_step(step, run_to_resume, step_inputs, run_dir)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1206, in reuse_or_prepare_step
    self.queue_recovery(missing_data, invoking_record=curr_RS)
  File "/usr/local/share/Kive/kive/sandbox/execute.py", line 1287, in queue_recovery
    assert not self.find_dataset(dataset_to_recover)
AssertionError
```

I think it happened because two runs of MiSeq used the same quality file, and both tried to restore the same `bad_cycles.csv`. The second one found that the dataset had already been restored and crashed. Can we just remove this assertion?

**Comment by donkirkby** [comment]
Irrelevant since we are removing support for old pipelines.
