### ISSUE TITLE
Retry after sbatch failure

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#784]
Twice in the last five days, I've seen socket timeout errors when a new job gets submitted through `sbatch`. I suspect that the head node gets heavily loaded and can't process the request fast enough.

When I looked closer, however, I found that the job actually did start. The `sbatch` command just hadn't heard back before timing out.

This isn't an urgent problem, because the MiCall pipeline waits a few seconds and then tries again. When it retries, it finds the run that was created by the first call and waits for it to complete. This would not work if the `sbatch` really failed and didn't just time out.

Adding a couple of retries should reduce the chances of this causing a problem. However, we can't use too long a delay, because the job gets submitted during a web request. A random delay between 500 and 1000ms is probably a good place to start.

Some options for how to retry:

1. Mark the run as failed if `sbatch` fails, so the `runcontainer` command won't do anything, even if it starts up. Then create another run.
2. Use `squeue` or `sacct` to see whether the first call to `sbatch` was successful. Create another run if the first one was not successful.

Here's an example error that I saw:

    sbatch: error: Batch job submission failed: Socket timed out on send/recv operation
    [:error] 2019-03-26 00:42:47[ERROR]django.request.handle_uncaught_exception(): Internal Server Error: /api/containerruns/
    [:error] Traceback (most recent call last):
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    [:error]     response = get_response(request)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    [:error]     response = self.process_exception_by_middleware(e, request)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    [:error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    [:error]     return view_func(*args, **kwargs)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/rest_framework/viewsets.py", line 116, in view
    [:error]     return self.dispatch(request, *args, **kwargs)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/rest_framework/views.py", line 495, in dispatch
    [:error]     response = self.handle_exception(exc)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    [:error]     self.raise_uncaught_exception(exc)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/rest_framework/views.py", line 492, in dispatch
    [:error]     response = handler(request, *args, **kwargs)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    [:error]     self.perform_create(serializer)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    [:error]     return func(*args, **kwargs)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/django/db/transaction.py", line 267, in __exit__
    [:error]     connection.set_autocommit(True)
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 416, in set_autocommit
    [:error]     self.run_and_clear_commit_hooks()
    [:error]   File "/path/to/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 651, in run_and_clear_commit_hooks
    [:error]     func()
    [:error]   File "/path/to/Kive/kive/container/models.py", line 1026, in schedule
    [:error]     env=child_env)
    [:error]   File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    [:error]     raise CalledProcessError(retcode, cmd, output=output)
    [:error] CalledProcessError: Command '[u'sbatch', u'-J', u'r61704 mixed-hcv', u'--parsable', u'--output', u'/data/kive/ContainerRuns/userdon_run61704_xBdym4/logs/job%J_node%N_stdout.txt', u'--error', u'/data/kive/ContainerRuns/userdon_run61704_xBdym4/logs/job%J_node%N_stderr.txt', u'-c', '4', u'--mem', '6000', u'-p', u'kive-slow', u'/path/to/Kive/kive/manage.py', u'runcontainer', '61704']' returned non-zero exit status 1

Then I looked in the slurm accounting data to see what happened to that job.

    $ sacct -u kive -o jobname%20,jobid | grep r61704
        r61704 mixed-hcv 1698485      
    $ sacct -o jobname%20,state,submit,start,end -j1698485
                 JobName      State              Submit               Start                 End 
    -------------------- ---------- ------------------- ------------------- ------------------- 
        r61704 mixed-hcv  COMPLETED 2019-03-26T00:42:36 2019-03-26T04:45:17 2019-03-26T05:23:42 
                   batch  COMPLETED 2019-03-26T04:45:17 2019-03-26T04:45:17 2019-03-26T05:23:42 
    $ 

You can see that it had already started when the error was reported. `sbatch` just didn't receive a confirmation in time.

**Comment by donkirkby** [comment]
Does this feature already exist in the old slurmlib module?
